### ISSUE TITLE
Поле customMultiSelectGrouped

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#10]
Нужен вот такой монстр, чтобы opions можно было группировать в optgroup

**Comment by baterflyrity** [comment]
@IvanHod , не понял)
Что значит группировать? Сортировать при отображении в выпадающем списке?

**Comment by baterflyrity** [comment]
Можно разделить группы подчёркиванием.
![image](https://user-images.githubusercontent.com/15788974/76890470-7aa25c80-6898-11ea-90ad-97d9193bc776.png)

Можно сделать [вкладки](http://jsfiddle.net/jxq1fpbm/1/).
![image](https://user-images.githubusercontent.com/15788974/76890796-0fa55580-6899-11ea-926d-de4e4a26491b.png)
********
![image](https://user-images.githubusercontent.com/15788974/76890873-2b106080-6899-11ea-80fd-6d3814e8aa75.png)
********
Но тогда поиск некорректно отображается (но работает по enter).
![image](https://user-images.githubusercontent.com/15788974/76891052-69a61b00-6899-11ea-8227-912a312dee3d.png)

**Comment by IvanHod** [comment]
С подчеркиванием норм смотрится, если поиск будет работать.

![image](https://user-images.githubusercontent.com/11644646/76898236-5ea5b780-68a6-11ea-9a1a-51aebf4e3b07.png)

**Comment by IvanHod** [comment]
![image](https://user-images.githubusercontent.com/11644646/77055713-75512900-69e2-11ea-8592-124732f1df2b.png)
Если не указать shortContent то получаю это (см. скрин)

+ Не работает поиск (свойство customMultiSelect)

**Comment by baterflyrity** [comment]
> Если не указать shortContent то получаю это (см. скрин)

А что конкретно ты указал?

> Не работает поиск (свойство customMultiSelect)

Поиск включается, только если элементов больше 5 штук.

**Comment by IvanHod** [comment]
> А что конкретно ты указал?
Группу и название

```
options: {
	'item 0': {
		group: 'Group 1',
		longContent: 'item 0',
	},
	'item 1': {
		group: 'Group 1',
		longContent: 'item 1'
	},
	'item 2': {
		group: 'Group 2',
		longContent: 'item 2'
	}
}
```

Сейчас попробовал указать только группу и shortContent, и работает ок. Непонятно что по дефолту. По идее должно быть полное название, и если пользователь хочет, он short добавляет, т.е. longContent - это дефолт.

**Comment by baterflyrity** [comment]
Думаю, стоит сделать как-то так:

`options: {
	'item 0': {
		group: 'Group 1',
		content: 'item 0',
	},
	'item 1': {
		group: 'Group 1',
		content: {
			short: 'item 1',
			long: 'This is item 1'
		}
	}
}`
