### ISSUE TITLE
Собирать Fomantic UI или использовать стандартные настройки?

### ISSUE THREAD

**Issue by baterflyrity** [baterflyrity/graph-editor.js#15]
Сборка из исходников с тонкой настройкой Fomantic UI требует отдельную папку `./vendor/fomantic-ui`. Надо решить, нужно ли это. Возможно, стоит использовать стандартную сборку из `./node_modules/fomantic-ui/dist`.

**Comment by IvanHod** [comment]
Не совсем понимаю разницу. Если точнее, то на что это влияет и что из этого вылезет?

**Comment by baterflyrity** [comment]
\+ Мы можем собирать только необходимые компоненты, кастомизировать их, выбирать разные темы оформления.
\- Мы дополнительно компируем исходники из пакета npm в `./vendor/fomantic-ui` и тратим много врмени на их сборку. При обновлении необходимо пересобирать нашу версию.

Они у себя пишут, что планируют поменять этот конвейер сборки, но пока не меняют((

**Comment by IvanHod** [comment]
Первый вариант вроде звучит приятнее.

**Comment by baterflyrity** [comment]
@IvanHod , там ошибка в форматировании была) Это всё мы получаем, если собираем из исходников.
