### ISSUE TITLE
При импорте графа, если есть обработчики onCreate, появляется ошибка

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#17]
Если добавить событие onCreate и импортировать граф, появляется ошибка с абстрактным сообщением.

```
ge.engine.onCreateNode.Subscribe(e => {
        if (!block) {
            block = true;

            reindexTheGraph();
            saveGraph();

            block = false;
        }
        return e;
    });

    ge.engine.onCreateEdge.Subscribe(e => {
        if (!block) {
            block = true;

            reindexTheGraph();
            saveGraph();

            block = false;
        }
        return e;
    });
```

**Comment by baterflyrity** [comment]
@IvanHod 

![изображение](https://user-images.githubusercontent.com/15788974/77888752-66396900-7275-11ea-82b7-7fd50fcd3a8e.png)

Не могу воспроизвести. Можешь подробнее описать: что такое импорт, какой граф? А лучше дай файл для примера.

Как вариант, можно использовать `ge.onCreateElement`.

**Comment by baterflyrity** [comment]
Если всё-таки нужно именно в графическом движке работать, то можешь объединить события для красоты.

    let onCreate = CreateNestedEvent('onCreate ', false, scope.engine.onCreateNode, scope.engine.onCreateEdge);

**Comment by IvanHod** [comment]
Пример графа по ссылке: https://drive.google.com/file/d/18vC92S0R1vfOmFm6XuyBptuk2v0L7koi/view?usp=sharing

объединение событий - круто смотрится.
 В reindexTheGraph() стоит setElement для обновления свойств узлов. Попробуй просто любое поле рандомного элемента обновлять

**Comment by baterflyrity** [comment]
Возможно, тут замешена ошибка #19.

**Comment by baterflyrity** [comment]
Ошибка исчезает, если указать `triggerEvents` равным `false`.

    ge.SetElement(... ,false);

Но, конечно, надо как-то это исправить в будущем. Думаю, создать больше событий, или убрать зацикливание, или выполнять callback'и в следующем фрейме.
