### ISSUE TITLE
Добавить максимально описывающие сообщения об ошибках

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#18]
Сейчас выводятся ошибки в формате "Упс, сломалось", нужно разобрать по кейсам и писать более осмысленно, иначе много времени на дебаг уходит.

**Comment by baterflyrity** [comment]
Кокнретизировал ошибки достаточно детально. Но может речь идёт о ошибках из библиотек?

**Comment by IvanHod** [comment]
Да, видимо. Пока закрываю тикет.
