### ISSUE TITLE
Разбить события на before и after

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#21]
А то сейчас приходится обходить в некоторых моментах эту штуку с помощью setTimeout...

**Comment by baterflyrity** [comment]
История стёрлась из-за отказа #b11a9dc62ab574a903c4d61094f8b73c2b81a84b, но теперь есть события: onCreateElementClass, onSetElementClass, onRemoveElementClass, onCreatePropertyClass, onSetPropertyClass, onRemovePropertyClass, onCreateElementStyle, onSetElementStyle, onRemoveElementStyle, onCreateElementProperty, onSetElementProperty, onRemoveElementProperty, onValidateElementType, onCreateElementType, onSetElementType, onRemoveElementType, onValidateElement, onCreateElement, onSetElement, onRemoveElement, onUpdateElementClass, onUpdatePropertyClass, onUpdateElementStyle, onUpdateElementProperty, onUpdateElementType, onUpdateElement, onAfterCreateElementClass, onAfterSetElementClass, onAfterRemoveElementClass, onAfterCreatePropertyClass, onAfterSetPropertyClass, onAfterRemovePropertyClass, onAfterCreateElementStyle, onAfterSetElementStyle, onAfterRemoveElementStyle, onAfterCreateElementProperty, onAfterSetElementProperty, onAfterRemoveElementProperty, onAfterValidateElementType, onAfterCreateElementType, onAfterSetElementType, onAfterRemoveElementType, onAfterValidateElement, onAfterCreateElement, onAfterSetElement, onAfterRemoveElement, onAfterUpdateElementClass, onAfterUpdatePropertyClass, onAfterUpdateElementStyle, onAfterUpdateElementProperty, onAfterUpdateElementType, onAfterUpdateElement.
