### ISSUE TITLE
Возникает ошибка в названии группы когда одна группа полностью выбрана

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#22]
Когда есть 2 группы, всё ок:
![image](https://user-images.githubusercontent.com/11644646/78132854-1e0d7880-7426-11ea-913b-a7a415f20e60.png)

Но если выбрать все варианты "инновационных", то должно остаться группа "Типовые", но остается "Инновационные":
![image](https://user-images.githubusercontent.com/11644646/78132901-2e255800-7426-11ea-8af7-e9c89df8d6c9.png)

**Comment by baterflyrity** [comment]
`$('.ui.dividing.header').filter((i,x)=>$(x).nextUntil('.ui.dividing.header').filter((j,y)=>$(y).is('.item')).toArray().every(y=>$(y).is('.filtered')))`

Raw сниппет для поиска "пустых" заголовков.
