### ISSUE TITLE
Выбор всех элементов группы по клике на название группы.

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#23]
Сейчас если 15 элементов в группе, то не очень удобные кликать на каждую.

По хорошему, нужно еще чтобы можно было "развыбрать" тоже по клику на название группы.

**Comment by baterflyrity** [comment]
Теперь заголовки групп работают так:
* выбрана хотя бы одна опция из группы - клик по заголовку убирает все опции группы из выборки
* не выбрано ни одной опции из группы - клик по заголовку добавляет все опции группы в выборку
* выбраны все опции из группы - заголовок скрывается
