### ISSUE TITLE
Поддержка создания customMultiSelect и customSelect без значений

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#24]
Сейчас при создании появляется ошибка. Т. е. нельзя даже поменять тип узла, так как окно редактирования не открывается.

**Comment by baterflyrity** [comment]
Не понятно, зачем создавать пустое свойство.

**Comment by baterflyrity** [comment]
Теперь ошибка выбрасывается, когда свойство без опций не является мжножественным и опциональным.

**Comment by IvanHod** [comment]
Так, а где это можно посмотреть/проверить?
Что значит опциональным?

**Comment by baterflyrity** [comment]
Опциональное - может не иметь значение (вернёт '' для optionalSelect/customOptionalSelect или [] для multiSelect/customMultiSelect).

Я это у себя протестил, а потом удалил. Можешь посмотреть в test1.html красный узел. Там изначально нет значения, а ошибка не выбрасывается (т.к. это множественный выбор).

**Comment by IvanHod** [comment]
Отлично!
