### ISSUE TITLE
Поддержка отсутствия значения в поле customSelect

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#25]
Сейчас если выбрал - то приходится смириться. Единственный шанс удалить узел, и потом добавить.

Можно при создании как-нибудь задавать is_required.

**Comment by baterflyrity** [comment]
Добавил классы свойств `optionalSelect` и `customOptionalSelect`. Пример в test1.html.

**Comment by IvanHod** [comment]
Там почему-то всё еще используется старое подключение библиотек с которым ничего не работает. После исправления на:

<pre>
< link rel="stylesheet" type="text/css" href="../dist/bundle.min.css">
<script type="text/javascript" src="../dist/bundle.min.js"></script>
</pre>

Выдает ошибку при создании
![image](https://user-images.githubusercontent.com/11644646/78333712-03a4dd80-7593-11ea-8470-dfb3842c7781.png)

**Comment by baterflyrity** [comment]
Ты точно из develop ветки проверял? У меня всё работает.
