### ISSUE TITLE
При physics.enabled = false вылетает ошибка

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#3]
`
physics: {
	enabled: true,
	stabilization: {
		fit: false
	}
},
`

Вылетает ошибка:
![image](https://user-images.githubusercontent.com/11644646/75993772-0ddba980-5f0b-11ea-9562-96568ac7fbd2.png)

Похожая [проблема](https://github.com/visjs/vis-network/issues/418).

Предлагаю выставлять `ge.engine.graph.physics.physicsEnabled` после стабилизации графа.

**Comment by baterflyrity** [comment]
Can not reproduce this bug.

**Comment by baterflyrity** [comment]
enabled: false - сейчас стал работать, граф не дергается, но только позиция не сохраняется

![изображение](https://user-images.githubusercontent.com/15788974/79962858-44588e00-8491-11ea-8de8-b9ab2b1bd21d.png)

**Comment by baterflyrity** [comment]
Вроде как пофиксили в vis.js. Надеюсь, больше не появится такая ошибка.
