### ISSUE TITLE
Некорректное обновление элемента

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#32]
Если из кода обновлять элемент как "ge.SetElement(...)", и задать ему пустое свойство, например {label: ''}, то в интерфейсе показывает '[object Object]' (см. скрин)
![image](https://user-images.githubusercontent.com/11644646/87798048-3037e900-c854-11ea-844c-2948fe35c00e.png)

**Comment by baterflyrity** [comment]
У меня всё работает как надо.
![image](https://user-images.githubusercontent.com/15788974/92722322-13112980-f370-11ea-9679-ad41da891624.png)
![image](https://user-images.githubusercontent.com/15788974/92722347-1efceb80-f370-11ea-8403-cd7454782f00.png)
![image](https://user-images.githubusercontent.com/15788974/92722385-31772500-f370-11ea-9cd1-1c535dead5ca.png)
@IvanHod, не вижу ошибки.

**Comment by IvanHod** [comment]
Закрываю исью, не могу воспроизвести.
