### ISSUE TITLE
Автоматическое удаление несвязанных рёбер

### ISSUE THREAD

**Issue by baterflyrity** [baterflyrity/graph-editor.js#35]
При удалении узлов, связанных рёбрами, эти рёбра визуально исчезают, но остаются в системе как лишняя нагрузка. Движок визуализации их не отображает, если не существует таких узлов.

С другой стороны, при пересоздании узлов рёбра автоматически восстанавливаются. 

@IvanHod, необходимо определить поведение рёбер: автоматическое восстановление (сейчас) или автоматическое удаление.

**Comment by IvanHod** [comment]
Автоматическое удаление.
С графом ведется постоянно взаимодействие, и такие ребра могут ввести в заблуждение.
