### ISSUE TITLE
Автоматическое преобразование ID в строки.

### ISSUE THREAD

**Issue by baterflyrity** [baterflyrity/graph-editor.js#6]
Обязательно указывать ID в строковом типе. Однако, если нарушить правило, всё сломается или будет криво работать. Надо сделать так, чтобы в любом случае ID приводились бы к строкам.

**Comment by IvanHod** [comment]
Либо у себя приводи, но лучше Exception кидать. Так как если какой-нибудь умник вместо id закинет, например, объект, тот приведется к [Object object] и тогда тотальный ад начнется...
