### ISSUE TITLE
Удаление рёбер

### ISSUE THREAD

**Issue by IvanHod** [baterflyrity/graph-editor.js#8]
Сейчас если удалить 2 узла, ребро остается висеть. Надо удалять такие "Пустые" ребра.

Также не работает ge.removeEdge(id). ge.removeElement - работает. Но зачем тогда функция removeEdge(id) нужна вообще?

**Comment by baterflyrity** [comment]
Не могу воспроизвести баг с висящими рёбрами.

> Также не работает ge.removeEdge(id). 

От старого API соталось, надо удалить.

**Comment by baterflyrity** [comment]
Can not reproduce this bug.
